version = '2'

[linters]
enable = [
  'exhaustive',
  'govet',
  'nilnil',
  'revive'
]

[linters.exclusions]
presets = [
  'comments',
#  'common-false-positives',
#  'legacy',
#  'std-error-handling'
]

[output]
show-stats = true
sort-results = true
