[settings]
minimum_release_age = "3d"

[env]
CHANGIE_CONFIG_PATH = "{{- config_root -}}/.config/changie.yaml"

[tools]
changie = '1'
cocogitto = '7'
editorconfig-checker = '3'
go = '1.26'
golangci-lint = '2'
goreleaser = '2'
lefthook = '2'

[tasks.build]
run = "goreleaser build --snapshot --clean --single-target"

[tasks.build-all]
run = "goreleaser build --snapshot --clean"

[tasks.lint]
run = [
    "golangci-lint run",
    "goreleaser check",
    "ec --config .config/editorconfig-checker.json",
    "cog --config .config/cog.toml check",
]

[tasks.test]
run = "go test -cover ./..."
