[settings]
minimum_release_age = "3d"

[env]
CHANGIE_CONFIG_PATH = "{{- config_root -}}/.config/changie.yaml"

[tools]
changie = '1'
cocogitto = '7'
editorconfig-checker = '3'
go = '1.26'
golangci-lint = '2.13.1'
goreleaser = '2'
lefthook = '2'

[tasks.build]
run = "goreleaser build --snapshot --clean --single-target"

[tasks.build-all]
run = "goreleaser build --snapshot --clean"

[tasks.lint-go]
sources = ["**/*.go", ".golangci.toml", "go.*"]
outputs = { auto = true }
run = "golangci-lint run"

[tasks.check-goreleaser]
sources = [".config/goreleaser.yaml"]
outputs = { auto = true }
run = "goreleaser check"

[tasks.editorconfig]
run = "ec --config .config/editorconfig-checker.json"

[tasks.check-git-history]
run = "cog --config .config/cog.toml check"

[tasks.lint]
depends = ["lint-go", "check-goreleaser", "editorconfig", "check-git-history"]

[tasks.test]
run = "go test -cover ./..."
