name: Confirm Releasability

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - unlabeled
    - labeled

jobs:
  unambiguous-next-version:
    name: Unambiguous next version
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        ref: ${{ github.event.pull_request.head.sha }} # here, we're not interested in the merge commit
        fetch-depth: '0'
    - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4

    - name: Confirm consistency of changelog and commit history
      run: |
        if [[ "$(ls .changes/unreleased/ | wc -l)" -eq 0 ]]; then
          echo "ℹ️ No recorded changes so far, so we'll be looking at a maintenance release"
          changie_next_version="$(changie next patch)"
        else
          changie_next_version="$(changie next auto)"
        fi
        cog_next_version="$(cog --config .config/cog.toml bump --dry-run --auto --skip-untracked)"
        echo "Changelog suggests version: ${changie_next_version}"
        echo "Commits suggest version:    ${cog_next_version}"
        {
          [[ "${cog_next_version}" == "${changie_next_version}" ]] \
            && echo "✅ Matches!";
        } || {
            echo "❌ Mismatch! Check your change types and commit messages!";
            exit 1;
        }

  contains-change-notes:
    name: Contains change notes
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'no changelog') }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        ref: ${{ github.event.pull_request.head.sha }} # here, we're not interested in the merge commit

    # Kudos: https://github.com/miniscruff/changie/blob/76fdd65ab31047fd6d506f800a6293f3b2a1ead0/.github/workflows/changelog-check.yml # editorconfig-checker-disable-line
    - name: "Check for changelog entries"
      uses: brettcannon/check-for-changed-files@d85c64d17b3c1d0ac57c9cc46ea39399b0d6fa71 # v1.2.2
      with:
        file-pattern: |
          .changes/unreleased/*.yaml
        skip-label: "no changelog"
        token: "${{ secrets.GITHUB_TOKEN }}"
        failure-message: |
          Missing a new changelog entry.
          Please add one with `changie new`, or
          apply label '${skip-label}' to the pull request."

    - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4

    - name: Test changelog assembly
      id: changie_dry_run
      run: |
        echo "Next version: $(changie next auto)"
        changie batch auto && echo "✅ Version changelog assembled"
        changie merge && echo "✅ Changelog assembled"
        echo "Prepared version: $(changie latest)"
        echo "next_version=$(changie latest)" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: docker-credential-1password_changes_${{ github.run_id }}-${{ github.run_attempt }}
        path: .changes/${{ steps.changie_dry_run.outputs.next_version }}.md
        if-no-files-found: error
        archive: false
        retention-days: 7
